In [40]:
#consider this given sequence
seq=[10,20,30,40,50,60,70,80,90]

#objective is to forecast next value in sequence

"""
prepare dataset for time series prediction
#create temporal dim based on time steps and target,let's take time step=3
x1    x2      x3      y
10    20      30      40
20    30      40      50
30    40      50      60
40    50      60      70
50    60      70      80
60    70      80      90
70    80      90      ?
"""

"\nprepare dataset for time series prediction\n#create temporal dim based on time steps and target,let's take time step=3\nx1    x2      x3      y\n10    20      30      40\n20    30      40      50\n30    40      50      60\n40    50      60      70\n50    60      70      80\n60    70      80      90\n70    80      90      ?\n"

In [41]:
import numpy as np
X=np.array([[10,20,30],[20,30,40],[30,40,50],[40,50,60],[50,60,70],[60,70,80]])
y=np.array([40,50,60,70,80,90])
print(X)
print(y)
n_steps=3
n_features=1  #no of series

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]


In [42]:
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

split_sequence(seq,3) 


(array([[10, 20, 30],
        [20, 30, 40],
        [30, 40, 50],
        [40, 50, 60],
        [50, 60, 70],
        [60, 70, 80]]), array([40, 50, 60, 70, 80, 90]))

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense

In [ ]:
model=Sequential()
model.add(LSTM(300,activation='relu',input_shape=(n_steps,n_features)))
model.add(Dense(1))
model.compile("adam","mse")
model.fit(X.reshape(X.shape[0],n_steps,n_features),y,epochs=300,verbose=0)
test_sample=np.array([[70,80,90]]).reshape(1,n_steps,n_features)
model.predict(test_sample)

array([[100.96175]], dtype=float32)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("drive/My Drive/dataset_new/time_series/Electric_Production.csv")
df.shape

(397, 2)

In [ ]:
df.head()

DATE  IPG2211A2N
0  1/1/1985     72.5052
1  2/1/1985     70.6720
2  3/1/1985     62.4502
3  4/1/1985     57.4714
4  5/1/1985     55.3151

In [ ]:
X,y=split_sequence(df.IPG2211A2N,5)
print(X[-1])
print(y[-1])

[108.9312  98.6154  93.6137  97.3359 114.7212]
129.4048


In [ ]:
X.shape

(392, 5)

In [ ]:
n_steps=5
n_features=1
model=Sequential()
model.add(LSTM(300,activation='relu',input_shape=(n_steps,n_features)))
model.add(Dense(1))
model.compile("adam","mse")
model.fit(X.reshape(X.shape[0],n_steps,n_features),y,epochs=300,verbose=0)
test_sample=np.array([[98.6154,93.6137,97.3359,114.7212,129.4048]]).reshape(1,n_steps,n_features)
model.predict(test_sample)

array([[114.75155]], dtype=float32)

In [ ]:
#consider 2 given sequences & output seq
seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])

#output sequence is element wise sum of seq1,seq2
out_seq = np.array([25, 45, 65, 85, 105, 125, 145, 165, 185])

#objective is to find next element in output seq if next elements are 100,105 in seq1,seq2 respectively 

#combine all 3 sequences into one 2d-array
sequences=[]
for i in range(0,9):#len of seq
	tmp_seq=[seq1[i],seq2[i],out_seq[i]]
	sequences.append(tmp_seq)
sequences=np.array(sequences) 
print(sequences)


[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [46]:
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

X,y=split_sequences(sequences,3)

In [48]:
X,y

(array([[[10, 15],
         [20, 25],
         [30, 35]],
 
        [[20, 25],
         [30, 35],
         [40, 45]],
 
        [[30, 35],
         [40, 45],
         [50, 55]],
 
        [[40, 45],
         [50, 55],
         [60, 65]],
 
        [[50, 55],
         [60, 65],
         [70, 75]],
 
        [[60, 65],
         [70, 75],
         [80, 85]],
 
        [[70, 75],
         [80, 85],
         [90, 95]]]), array([ 65,  85, 105, 125, 145, 165, 185]))

In [50]:
n_steps=3
n_features=2

model=Sequential()
model.add(LSTM(300,activation='relu',input_shape=(n_steps,n_features)))
model.add(Dense(1))
model.compile("adam","mse")
model.fit(X.reshape(X.shape[0],n_steps,n_features),y,epochs=300,verbose=0)
test_sample=np.array([[80,85],[90,95],[100,105]]).reshape(1,n_steps,n_features)
model.predict(test_sample)


array([[205.34792]], dtype=float32)