In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('c:/dataset/classification/iris.csv')

In [3]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [4]:
from sklearn.svm import SVC

In [5]:
svc=SVC(kernel='linear',decision_function_shape='ovo',probability=True)

In [6]:
svc.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [29]:
test_sample=X[120]

In [30]:
test_sample

array([6.9, 3.2, 5.7, 2.3])

In [31]:
svc.decision_function([test_sample])

array([[-3.98340727, -1.71069576, -2.18480702]])

In [32]:
svc.predict_proba([test_sample])

array([[0.00483483, 0.00602494, 0.98914024]])

In [33]:
svc.predict([test_sample])

array([2], dtype=int64)

In [25]:
import numpy as np
z=np.abs(svc.coef_).sum(axis=1)
svc.decision_function([test_sample])/z

array([[0.75885451, 1.26359843, 1.78036997]])

In [18]:
svc.classes_

array([0, 1, 2], dtype=int64)

In [19]:
svc.class_weight_

array([1., 1., 1.])