In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.datasets import load_iris

In [64]:
iris = load_iris()
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [65]:
iris["data"].shape,iris["target"].shape,

((150, 4), (150,))

In [66]:
X_train, X_test, y_train, y_test = train_test_split(iris["data"], iris["target"], test_size=0.33, random_state=42)

In [67]:
scaler = StandardScaler()
Xtrain = scaler.fit_transform(X_train)
Xtest = scaler.transform(X_test)

In [68]:
svc = SVC(kernel="linear", decision_function_shape="ov0", probability=True)
svc.fit(Xtrain, y_train)
print(svc.coef_,"\n intercept: ", svc.intercept_)

[[-0.43261323  0.31763493 -0.86814647 -0.91624358]
 [-0.06326729  0.13297553 -0.54149147 -0.54651846]
 [ 0.21793362  0.70071456 -2.19639387 -2.09850754]] 
 intercept:  [-1.54107568 -0.33848249  2.73728143]


In [69]:
svc.decision_function([X_test[0]])

array([[-8.4704193 , -3.55291358, -6.81258299]])

In [70]:
svc.predict([X_test[0]])

array([2])

In [72]:
y_test[0]

1

In [71]:
svc.predict_proba([X_test[0]])

array([[2.11542165e-08, 2.53805446e-08, 9.99999953e-01]])

In [74]:
svc.score([X_test[0]], [y_test[0]])

0.0