In [1]:
import pandas as pd
df=pd.read_csv('../../dataset/regression/salary_1_variable.csv')
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [2]:
from sklearn.linear_model import SGDRegressor

In [3]:
sgd=SGDRegressor(verbose=True)
sgd.fit(X,y)

-- Epoch 1
Norm: 12585.26, NNZs: 1, Bias: 1983.473599, T: 30, Avg. loss: 325557788.064943
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 12693.21, NNZs: 1, Bias: 2605.548935, T: 60, Avg. loss: 80757994.346439
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 12913.11, NNZs: 1, Bias: 3159.723968, T: 90, Avg. loss: 78067231.433204
Total training time: 0.01 seconds.
-- Epoch 4
Norm: 13060.59, NNZs: 1, Bias: 3639.620921, T: 120, Avg. loss: 74559261.021576
Total training time: 0.01 seconds.
-- Epoch 5
Norm: 12383.81, NNZs: 1, Bias: 3973.355972, T: 150, Avg. loss: 71894951.355158
Total training time: 0.01 seconds.
-- Epoch 6
Norm: 12675.57, NNZs: 1, Bias: 4416.648941, T: 180, Avg. loss: 70759882.001694
Total training time: 0.01 seconds.
-- Epoch 7
Norm: 12727.93, NNZs: 1, Bias: 4801.189876, T: 210, Avg. loss: 68614872.431954
Total training time: 0.01 seconds.
-- Epoch 8
Norm: 12443.60, NNZs: 1, Bias: 5114.036590, T: 240, Avg. loss: 66674914.580079
Total training time: 0.01 seconds.
--

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=True,
             warm_start=False)

## Perceptron for Regression Manually

In [4]:
import numpy as np
def output_neuron(X,w,b):
    yhat=X@w+b
    return yhat

In [5]:
def loss(yhat,ytrue):
    return (np.sum(np.square(yhat-ytrue)))/2*len(yhat)

In [6]:
def update_parameters(X,ytrue,w,b,lr):
    bias_derv=np.sum((X@w+b)-ytrue)/len(ytrue)
    weight_derv=np.sum(((X@w+b)-ytrue)*X)/len(ytrue)
    
    new_bias=b-lr*bias_derv
    new_weight=w-lr*weight_derv
    return new_bias,new_weight

In [7]:
w=np.random.uniform(0,1,1) #here w is 1d array(lower limit,upperlimit,size)
b=np.random.random()
yhat=output_neuron(X,w,b)
print(loss(yhat,y))
print("initial parameters:",w,b)
for epoch in range(50):
    b,w=update_parameters(X,y,w,b,.002)
    yhat=output_neuron(X,w,b)
    print(loss(yhat,y))

2926077402716.18
initial parameters: [0.53895257] 0.30567393564733103
2037989346751.441
638786142263.7491
635614160760.0088
164761411531.95065
263337553249.11765
83801327189.76294
155015647176.73053
79442033492.49974
119434285493.23494
85502946115.4438
106160904338.64311
90354445178.89027
100661138154.72087
93153272692.12146
98215439209.569
94614038209.12686
97082114494.33832
95346150341.93028
96545255520.97606
95706482002.02722
96288081054.0665
95882336873.30379
96164199016.92503
95967815792.94357
96104361796.16481
96009284895.81973
96075420996.07306
96029384412.82758
96061414503.21915
96039121992.89536
96054633656.38246
96043838514.73543
96051350404.47896
96046122781.71568
96049760553.8609
96047229022.59155
96048990672.40424
96047764747.45828
96048617852.69061
96048024182.54474
96048437311.00407
96048149818.2545
96048349881.5285
96048210659.24364
96048307542.67422
96048240122.37106
96048287039.51718
96048254390.30655
96048277110.58432
96048261299.75354


In [8]:
w,b

(array([14287.27699295]), 89.93389250770889)

In [9]:
new_sample=np.array([[10],[3]])
output_neuron(new_sample,w,b)

array([142962.70382203,  42951.76487137])

In [11]:
df=pd.read_csv('../../dataset/regression/salary_2_variable.csv')
df.Gender=df.Gender.map({'Male':0,'Female':1})

In [12]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
df

Exp  Gender  Salary
0  1.1       0   41000
1  1.3       1   36205
2  1.5       1   37731
3  2.0       0   43525
4  2.2       1   39891
5  2.9       0   56642
6  3.0       0   60150
7  3.2       1   56240
8  3.3       0   59150
9  3.8       0   61000

In [13]:
def update_parameters(X,ytrue,w,b,lr):
    bias_derv=np.sum((X@w+b)-ytrue)/len(ytrue)
    weight1_derv=np.sum(((X[:,[0]]@w[0].reshape(1,-1)+b)-ytrue)*X[:,[0]])/len(ytrue)
    weight2_derv=np.sum(((X[:,[1]]@w[1].reshape(1,-1)+b)-ytrue)*X[:,[1]])/len(ytrue)
    
    new_bias=b-lr*bias_derv
    new_weight1=w[0]-lr*weight1_derv
    new_weight2=w[1]-lr*weight2_derv
    
    return new_bias,np.array([new_weight1,new_weight2])

In [14]:
w=np.random.uniform(0,1,2)
b=np.random.random()
print("initial parameters:\n",w,b,output_neuron(X,w,b))
for epoch in range(60):
    b,w=update_parameters(X,y,w,b,.001)
    yhat=output_neuron(X,w,b)
    if(epoch%10==0):
        print(loss(yhat,y))

initial parameters:
 [0.34286537 0.27848346] 0.8987953433738299 [1.27594726 1.62300379 1.69157686 1.58452609 1.93158262 1.89310493
 1.92739147 2.274448   2.03025108 2.20168377]
110247231433.54623
31936786970.527023
11330829005.254087
5775693870.718916
4313959451.930315
4050199574.9081726


In [15]:
w,b

(array([17278.51360147, 10372.95110476]), 844.5836190436737)

In [16]:
test_sample=np.array([[3.4,0],[3.4,1],[5,1],[5,0],[3.8,0],[3.3,0]])
output_neuron(test_sample,w,b)

array([59591.52986403, 69964.48096879, 97610.10273114, 87237.15162637,
       66502.93530461, 57863.67850388])