In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('c:/dataset/classification/fruits.csv')
df

diameter  weight FruitName
0        3.0      30    Banana
1        6.0     100     Apple
2        6.1      95     Apple
3        3.2      35    Banana
4        5.5      80     Apple
5        7.1     120    Banana
6        2.5      60    Banana
7        2.3     100    Banana
8        4.8      70     Apple
9        4.8      79     Apple
10       5.8     120     Apple
11       2.6      85    Banana
12       6.0     110     Apple
13       6.3      95     Apple
14       3.0      40    Banana
15       3.5      25    Banana
16       5.5     100     Apple
17       7.5     120     Apple
18       2.5      50    Banana
19       2.7      40    Banana
20       4.8      90     Apple
21       5.8      90     Apple

In [3]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [4]:
X

array([[  3. ,  30. ],
       [  6. , 100. ],
       [  6.1,  95. ],
       [  3.2,  35. ],
       [  5.5,  80. ],
       [  7.1, 120. ],
       [  2.5,  60. ],
       [  2.3, 100. ],
       [  4.8,  70. ],
       [  4.8,  79. ],
       [  5.8, 120. ],
       [  2.6,  85. ],
       [  6. , 110. ],
       [  6.3,  95. ],
       [  3. ,  40. ],
       [  3.5,  25. ],
       [  5.5, 100. ],
       [  7.5, 120. ],
       [  2.5,  50. ],
       [  2.7,  40. ],
       [  4.8,  90. ],
       [  5.8,  90. ]])

In [16]:
import numpy as np
w1=np.array([2,3])#w11,w12
w2=np.array([1,3])#w21,w21
w3=np.array([2,2])#w31,w32
b1=2
b2=1
b3=3

In [17]:
3*2+30*3+2

98

In [18]:
X[0]

array([ 3., 30.])

In [19]:
w1.T@X[0]+b1

98.0

In [20]:
for x in X:
    print(w1.T@x+b1)

98.0
314.0
299.2
113.4
253.0
376.2
187.0
306.6
221.6
248.6
373.6
262.2
344.0
299.6
128.0
84.0
313.0
377.0
157.0
127.4
281.6
283.6


In [21]:
X@w1+b1

array([ 98. , 314. , 299.2, 113.4, 253. , 376.2, 187. , 306.6, 221.6,
       248.6, 373.6, 262.2, 344. , 299.6, 128. ,  84. , 313. , 377. ,
       157. , 127.4, 281.6, 283.6])

In [22]:
X@w2+b2

array([ 94. , 307. , 292.1, 109.2, 246.5, 368.1, 183.5, 303.3, 215.8,
       242.8, 366.8, 258.6, 337. , 292.3, 124. ,  79.5, 306.5, 368.5,
       153.5, 123.7, 275.8, 276.8])

In [23]:
X@w3+b3

array([ 69. , 215. , 205.2,  79.4, 174. , 257.2, 128. , 207.6, 152.6,
       170.6, 254.6, 178.2, 235. , 205.6,  89. ,  60. , 214. , 258. ,
       108. ,  88.4, 192.6, 194.6])

In [26]:
W=np.array([w1,w2,w3])
W

array([[2, 3],
       [1, 3],
       [2, 2]])

In [28]:
B=np.array([b1,b2,b3])
B

array([2, 1, 3])

In [30]:
Y=W@X.T+B.reshape(-1,1)

In [31]:
Y.shape

(3, 22)

In [32]:
B

array([2, 1, 3])

In [33]:
B.reshape(-1,1)

array([[2],
       [1],
       [3]])

In [34]:
Y

array([[ 98. , 314. , 299.2, 113.4, 253. , 376.2, 187. , 306.6, 221.6,
        248.6, 373.6, 262.2, 344. , 299.6, 128. ,  84. , 313. , 377. ,
        157. , 127.4, 281.6, 283.6],
       [ 94. , 307. , 292.1, 109.2, 246.5, 368.1, 183.5, 303.3, 215.8,
        242.8, 366.8, 258.6, 337. , 292.3, 124. ,  79.5, 306.5, 368.5,
        153.5, 123.7, 275.8, 276.8],
       [ 69. , 215. , 205.2,  79.4, 174. , 257.2, 128. , 207.6, 152.6,
        170.6, 254.6, 178.2, 235. , 205.6,  89. ,  60. , 214. , 258. ,
        108. ,  88.4, 192.6, 194.6]])