In [1]:
import tensorflow as tf
import numpy as np

In [2]:
t1 = tf.constant([10,20,30])
print(t1)

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [4]:
t1=tf.constant(range(10))
t1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [6]:
t1=tf.constant(np.arange(5))
t1

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [7]:
t2=tf.Variable([10,20,30])
t2

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [8]:
t2=tf.Variable(range(10))
t2

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [9]:
t2=tf.Variable(np.arange(5))
t2

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [10]:
t3=tf.constant([[10,20,30],[20,30,40]])
t3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [20, 30, 40]], dtype=int32)>

In [11]:
t3=tf.constant([10,20,30,40,50,60],shape=(2,3))
t3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [12]:
t3.numpy()

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)

In [13]:
t3=tf.constant([10,20,30,40,50,60],shape=(2,3),dtype='float32')
t3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [14]:
t3.numpy()

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [16]:
t3=tf.constant([10,20,30,40,50,60],shape=(2,3),dtype='float32',name='age_const_tensor')
t3.numpy()

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [17]:
t3=tf.Variable([[10,20,30],[40,50,60]],dtype='float32',name='age_const_tensor')
t3.numpy()

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [19]:
t1=tf.constant([10,20,-5,50,40,30,20])
t2=tf.constant([40,20,-2,10,40,30,20])
print(tf.math.minimum(t1,t2)) # return mininum list
print(tf.math.reduce_min(t1)) # return minimum number
print(tf.math.maximum(t1,t2)) # return max list
print(tf.math.reduce_max(t1)) # return max number

tf.Tensor([10 20 -5 10 40 30 20], shape=(7,), dtype=int32)
tf.Tensor(-5, shape=(), dtype=int32)
tf.Tensor([40 20 -2 50 40 30 20], shape=(7,), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)


In [20]:
tf.math.reduce_sum(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=165>

In [21]:
tf.math.reduce_mean(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [22]:
tf.math.argmax(t1)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [23]:
tf.math.argmin(t1)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [27]:
m1=tf.constant([[1,2],[3,4]])
m2=tf.constant([[10,20],[30,40]])
print(tf.math.multiply(m1,m2))
print(tf.matmul(m1,m2))
print(m1*m2)
print(m1@m2)

tf.Tensor(
[[ 10  40]
 [ 90 160]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 70 100]
 [150 220]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 10  40]
 [ 90 160]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 70 100]
 [150 220]], shape=(2, 2), dtype=int32)


In [28]:
tf.reduce_min(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=-5>

In [29]:
m1=np.random.randint(1,100,(1000,1000))
m2=np.random.randint(1,100,(1000,1000))
t1=tf.constant(m1)
t2=tf.constant(m2)

#### Commented out IPython magic to ensure Python compatibility.


In [30]:
%%time
m1@m2

CPU times: user 1.55 s, sys: 0 ns, total: 1.55 s
Wall time: 1.59 s


array([[2570992, 2584694, 2522793, ..., 2534915, 2519526, 2541713],
       [2388628, 2462304, 2418778, ..., 2459779, 2443087, 2384736],
       [2480351, 2562360, 2476705, ..., 2511435, 2463246, 2447212],
       ...,
       [2477042, 2560379, 2440560, ..., 2556661, 2483286, 2445759],
       [2576938, 2566920, 2538959, ..., 2557425, 2531198, 2528579],
       [2470068, 2510120, 2451331, ..., 2516047, 2510569, 2476854]])

#### Commented out IPython magic to ensure Python compatibility.

In [31]:
%%time
t1@t2

CPU times: user 617 ms, sys: 0 ns, total: 617 ms
Wall time: 284 ms


<tf.Tensor: shape=(1000, 1000), dtype=int64, numpy=
array([[2570992, 2584694, 2522793, ..., 2534915, 2519526, 2541713],
       [2388628, 2462304, 2418778, ..., 2459779, 2443087, 2384736],
       [2480351, 2562360, 2476705, ..., 2511435, 2463246, 2447212],
       ...,
       [2477042, 2560379, 2440560, ..., 2556661, 2483286, 2445759],
       [2576938, 2566920, 2538959, ..., 2557425, 2531198, 2528579],
       [2470068, 2510120, 2451331, ..., 2516047, 2510569, 2476854]])>

In [32]:
tf.random.normal(shape=(30,))

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([ 0.27812386,  0.9044579 ,  0.89654624,  0.70584995,  0.21555619,
        1.813479  , -0.6267387 ,  0.732129  , -1.3851398 ,  1.0629038 ,
        0.37264764, -1.3765893 , -0.7575679 ,  1.4370359 ,  0.4902318 ,
        0.1888148 ,  0.81346107,  1.5224409 ,  0.8849572 , -1.4294279 ,
       -0.43182474, -0.27700266,  0.3442905 ,  1.3467984 ,  0.35653841,
        1.1669747 , -0.3079742 , -0.53279227, -2.1496825 , -0.8380482 ],
      dtype=float32)>

In [33]:
tf.random.truncated_normal(shape=(30,))

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([-0.13650654, -0.8344724 ,  0.67790085, -1.2078537 , -0.1341163 ,
        0.62945443,  0.21340172, -0.22381566,  1.3552368 ,  0.14254561,
        0.77239716,  0.5113895 ,  0.49383008, -0.4085038 ,  0.64850765,
       -0.34715864, -0.73739535,  0.33583087,  0.1668239 , -0.8812224 ,
        0.82890296, -0.62302876, -0.5456427 , -1.2223084 ,  0.10259608,
       -0.07339627,  0.21567954, -0.05922334,  0.47661036, -0.9406068 ],
      dtype=float32)>

In [34]:
tf.random.uniform(shape=(30,))

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.142277  , 0.76836383, 0.48004532, 0.09431279, 0.46730697,
       0.12683034, 0.92016387, 0.3504907 , 0.9234226 , 0.2478056 ,
       0.20468712, 0.7705864 , 0.8820889 , 0.56688154, 0.587319  ,
       0.06721568, 0.24113071, 0.8437793 , 0.9320959 , 0.14448285,
       0.6520598 , 0.15252006, 0.42050636, 0.23914671, 0.11651409,
       0.35473847, 0.486987  , 0.05901408, 0.14635682, 0.7650815 ],
      dtype=float32)>