In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../../dataset/classification/iris.csv')

In [3]:
df['class'].unique()

array([0, 1, 2])

In [4]:
df

sepal_length  sepal_width  petal_length  petal_width  class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
5             5.4          3.9           1.7          0.4      0
6             4.6          3.4           1.4          0.3      0
7             5.0          3.4           1.5          0.2      0
8             4.4          2.9           1.4          0.2      0
9             4.9          3.1           1.5          0.1      0
10            5.4          3.7           1.5          0.2      0
11            4.8          3.4           1.6          0.2      0
12            4.8          3.0           1.4          0.1      0
13            4.3          3.0           1.1          0.1      0
14            5.8          4.0           1.2          0.2      0
15            5.7          4.4           1.5          0.4      0
16            5.4          3.9           1.3          0.4      0
17            5.1          3.5           1.4          0.3      0
18            5.7          3.8           1.7          0.3      0
19            5.1          3.8           1.5          0.3      0
20            5.4          3.4           1.7          0.2      0
21            5.1          3.7           1.5          0.4      0
22            4.6          3.6           1.0          0.2      0
23            5.1          3.3           1.7          0.5      0
24            4.8          3.4           1.9          0.2      0
25            5.0          3.0           1.6          0.2      0
26            5.0          3.4           1.6          0.4      0
27            5.2          3.5           1.5          0.2      0
28            5.2          3.4           1.4          0.2      0
29            4.7          3.2           1.6          0.2      0
..            ...          ...           ...          ...    ...
120           6.9          3.2           5.7          2.3      2
121           5.6          2.8           4.9          2.0      2
122           7.7          2.8           6.7          2.0      2
123           6.3          2.7           4.9          1.8      2
124           6.7          3.3           5.7          2.1      2
125           7.2          3.2           6.0          1.8      2
126           6.2          2.8           4.8          1.8      2
127           6.1          3.0           4.9          1.8      2
128           6.4          2.8           5.6          2.1      2
129           7.2          3.0           5.8          1.6      2
130           7.4          2.8           6.1          1.9      2
131           7.9          3.8           6.4          2.0      2
132           6.4          2.8           5.6          2.2      2
133           6.3          2.8           5.1          1.5      2
134           6.1          2.6           5.6          1.4      2
135           7.7          3.0           6.1          2.3      2
136           6.3          3.4           5.6          2.4      2
137           6.4          3.1           5.5          1.8      2
138           6.0          3.0           4.8          1.8      2
139           6.9          3.1           5.4          2.1      2
140           6.7          3.1           5.6          2.4      2
141           6.9          3.1           5.1          2.3      2
142           5.8          2.7           5.1          1.9      2
143           6.8          3.2           5.9          2.3      2
144           6.7          3.3           5.7          2.5      2
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0          

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
lr=LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=150)

In [7]:
X=df.iloc[:,0:-1].values
y=df.iloc[:,-1].values
lr.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=150,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
lr.intercept_

array([  9.85357271,   2.23426867, -12.08784138])

In [9]:
lr.coef_

array([[-0.42406205,  0.96708687, -2.51731534, -1.07921448],
       [ 0.53483014, -0.32130666, -0.20632206, -0.9443764 ],
       [-0.11076809, -0.64578021,  2.7236374 ,  2.02359088]])

In [10]:
sample=[5.1,3.5,1.4,0.2]

In [11]:
z0=lr.coef_[0][0]*sample[0]+lr.coef_[0][1]*sample[1]+lr.coef_[0][2]*sample[2]+lr.coef_[0][3]*sample[3]+lr.intercept_[0]
z1=lr.coef_[1][0]*sample[0]+lr.coef_[1][1]*sample[1]+lr.coef_[1][2]*sample[2]+lr.coef_[1][3]*sample[3]+lr.intercept_[1]
z2=lr.coef_[2][0]*sample[0]+lr.coef_[2][1]*sample[1]+lr.coef_[2][2]*sample[2]+lr.coef_[2][3]*sample[3]+lr.intercept_[2]


In [12]:
print(z0,z1,z2)

7.335575946450277 3.359602882447483 -10.69517882889773


In [13]:
lr.decision_function([sample])

array([[  7.33557595,   3.35960288, -10.69517883]])

In [14]:
import numpy as np

In [15]:
prob0=np.exp(z0)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
prob1=np.exp(z1)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
prob2=np.exp(z2)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
print(prob0,prob1,prob2)

0.9815844435181765 0.018415541985082995 1.4496740452848575e-08


In [16]:
probs=lr.predict_proba([sample])

In [17]:
np.max(probs)

0.9815844435181766

In [18]:
np.argmax(probs)

0

In [19]:
lr.predict([sample])

array([0])