In [22]:
from keras.preprocessing.text import Tokenizer
import numpy as np

In [23]:
corpus=['food is # good! _@ 2019',
		'& Food # is * tasty',
		'quality is Good',
		'service is Poor poor means very poor',
		'it is too costly',
		'cheap quality']
target=[1,1,1,0,0,0]    

In [47]:
tkn=Tokenizer()
tkn.fit_on_texts(corpus)

In [48]:
print(tkn.word_index)
print(len(tkn.word_index))
print(tkn.word_counts) 
print(tkn.word_docs)
print(tkn.document_count)

{'is': 1, 'poor': 2, 'food': 3, 'good': 4, 'quality': 5, '2019': 6, 'tasty': 7, 'service': 8, 'means': 9, 'very': 10, 'it': 11, 'too': 12, 'costly': 13, 'cheap': 14}
14
OrderedDict([('food', 2), ('is', 5), ('good', 2), ('2019', 1), ('tasty', 1), ('quality', 2), ('service', 1), ('poor', 3), ('means', 1), ('very', 1), ('it', 1), ('too', 1), ('costly', 1), ('cheap', 1)])
defaultdict(<class 'int'>, {'2019': 1, 'good': 2, 'food': 2, 'is': 5, 'tasty': 1, 'quality': 2, 'means': 1, 'service': 1, 'very': 1, 'poor': 1, 'costly': 1, 'too': 1, 'it': 1, 'cheap': 1})
6


In [49]:
X=tkn.texts_to_matrix(corpus,mode='binary')
y=np.array(target)

In [50]:
print(X.shape)
X

(6, 15)


array([[0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
import pandas as pd

In [117]:
df=pd.read_csv("drive/My Drive/dataset_dl/sentiment/spam_ham.txt",delimiter="\t",names=['msg_type','msg'])
print(df.shape)
df.msg_type=df.msg_type.map({'spam':0,'ham':1})
df.head(10)
df.msg_type.value_counts()

(5572, 2)


1    4825
0     747
Name: msg_type, dtype: int64

In [101]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.msg,df.msg_type,random_state=10)

In [102]:
tkn=Tokenizer()
tkn.fit_on_texts(X_train)
print(len(tkn.word_index))

7689


In [118]:
X_train_new=tkn.texts_to_matrix(X_train)
X_test_new=tkn.texts_to_matrix(X_test)

In [104]:
from tensorflow.keras.layers import Dense,Dropout,Conv1D,Flatten,MaxPooling1D
from tensorflow.keras.models import Sequential

In [105]:
model=Sequential()
model.add(Dense(50,activation='relu',input_shape=(X_train_new.shape[1],)))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train_new,y_train,epochs=5)

Epoch 1/5
131/131 [==============================] - 1s 4ms/step - loss: 0.2741 - accuracy: 0.9318
Epoch 2/5
131/131 [==============================] - 1s 4ms/step - loss: 0.0399 - accuracy: 0.9933
Epoch 3/5
131/131 [==============================] - 1s 4ms/step - loss: 0.0104 - accuracy: 0.9988
Epoch 4/5
131/131 [==============================] - 1s 4ms/step - loss: 0.0040 - accuracy: 0.9993
Epoch 5/5
131/131 [==============================] - 1s 4ms/step - loss: 0.0019 - accuracy: 1.0000


In [106]:
model.evaluate(X_test_new,y_test)

44/44 [==============================] - 0s 2ms/step - loss: 0.0880 - accuracy: 0.9813


[0.08804430812597275, 0.9813352227210999]

In [112]:
test_sample=["get free talktime of rs 2000 share the link in 10 gropus"]
test_sample_new=tkn.texts_to_matrix(test_sample)
model.predict(test_sample_new)

array([[0.99254525]], dtype=float32)

In [82]:
model_cnn=Sequential()
model_cnn.add(Conv1D(32,3,activation='relu',input_shape=(X_train_new.shape[1],1)))
model_cnn.add(MaxPooling1D())
model_cnn.add(Flatten())
model_cnn.add(Dense(1,activation='sigmoid'))
model_cnn.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model_cnn.fit(X_train_new.reshape(X_train_new.shape[0],X_train_new.shape[1],1),y_train,epochs=5)

Epoch 1/5
131/131 [==============================] - 13s 97ms/step - loss: 0.2923 - accuracy: 0.8940
Epoch 2/5
131/131 [==============================] - 13s 97ms/step - loss: 0.0809 - accuracy: 0.9780
Epoch 3/5
131/131 [==============================] - 13s 98ms/step - loss: 0.0437 - accuracy: 0.9871
Epoch 4/5
131/131 [==============================] - 13s 97ms/step - loss: 0.0259 - accuracy: 0.9935
Epoch 5/5
131/131 [==============================] - 13s 97ms/step - loss: 0.0157 - accuracy: 0.9962


In [88]:
model_cnn.evaluate(X_test_new.reshape(X_test_new.shape[0],X_test_new.shape[1],1),y_test)

44/44 [==============================] - 2s 40ms/step - loss: 0.0839 - accuracy: 0.9742


[0.08385652303695679, 0.9741564989089966]

In [113]:
test_sample=["get free talktime of rs 2000 share the link in 10 gropus"]
test_sample_new=tkn.texts_to_matrix(test_sample)
test_sample_new=test_sample_new.reshape(test_sample_new.shape[0],test_sample_new.shape[1],1)
model_cnn.predict(test_sample_new)

array([[0.9119481]], dtype=float32)

In [76]:
df=pd.read_json("drive/My Drive/dataset_dl/sentiment/news.json",lines=True)
print(df.shape)
df.head()


(1436, 6)


category  ...       date
0          CRIME  ... 2018-05-26
1  ENTERTAINMENT  ... 2018-05-26
2  ENTERTAINMENT  ... 2018-05-26
3  ENTERTAINMENT  ... 2018-05-26
4  ENTERTAINMENT  ... 2018-05-26

[5 rows x 6 columns]