In [3]:
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [4]:
df =  pd.read_csv('../dataset/classification/fruits.csv')

In [8]:
kncc = KNeighborsClassifier()

In [6]:
X_train = df.iloc[:15, 0:-1].values
y_train = df.iloc[:15, -1].values
X_test = df.iloc[15:, 0:-1].values
y_test = df.iloc[15:, -1].values

In [9]:
for i in range(3,10):
    kncc = KNeighborsClassifier(n_neighbors=i)
    kncc.fit(X_train, y_train)
    pred_train = kncc.predict(X_train)
    pred_test = kncc.predict(X_test)
    train_acc = accuracy_score(y_train, pred_train)
    test_acc = accuracy_score(y_test, pred_test)
    print(i, train_acc*100, test_acc*100)

3 73.33333333333333 100.0
4 73.33333333333333 100.0
5 73.33333333333333 100.0
6 73.33333333333333 100.0
7 80.0 100.0
8 80.0 100.0
9 80.0 100.0


In [11]:
kncc.predict([[4.2,90]])

array(['Apple'], dtype=object)

Feature Scalling:
----------------
> it is process to make all values of all features within a range. so that all features will contribute equally to predict the output.

    x1           x2
    ---------------
    1            20
    2.8          45
    1.5          35
    2.1          56.4
    
    range of x1: (1 to 2.8)
    range of x2:(20 to 56.4)

Techniques of Feature Scalling:
------------------------------
   1. MinMax Scalar
   2. Standar Scalar
   3. Binarizer
   4. MaxAbsScalar
   5. Normalizer
    

In [12]:
X = [[1,20], [2.8, 45], [1.5, 35], [2.1, 56.4]]

In [14]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Binarizer, MaxAbsScaler, Normalizer

In [17]:
minMaxScal = MinMaxScaler(feature_range=(0,1))
minMaxScal

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
minMaxScal.fit(X) #find min and max for the feature

MinMaxScaler(copy=True, feature_range=(0, 1))

In [25]:
newX = minMaxScal.transform(X) # scalee the values using formula

In [26]:
newX

array([[0.        , 0.        ],
       [1.        , 0.68681319],
       [0.27777778, 0.41208791],
       [0.61111111, 1.        ]])

In [31]:
newX = minMaxScal.fit_transform(X)
newX

array([[0.        , 0.        ],
       [1.        , 0.68681319],
       [0.27777778, 0.41208791],
       [0.61111111, 1.        ]])

In [32]:
sc = MaxAbsScaler()

In [33]:
newX = sc.fit_transform(X)
newX

array([[0.35714286, 0.35460993],
       [1.        , 0.79787234],
       [0.53571429, 0.62056738],
       [0.75      , 1.        ]])

In [34]:
import numpy as np

In [36]:
np.array(X)

array([[ 1. , 20. ],
       [ 2.8, 45. ],
       [ 1.5, 35. ],
       [ 2.1, 56.4]])

In [37]:
sc = StandardScaler()

In [45]:
newX = sc.fit_transform(X)

In [46]:
std_x1 = np.std([1,2.8, 1.5, 2.1])

In [47]:
std_x2 = np.std([30,40,20,40])

In [48]:
mean_x1 = np.mean([1,4,2,3])

In [49]:
mean_x2 = np.mean([20, 45,35, 56.4])

In [50]:
(1-mean_x1) / std_x1

-2.229882438741499

In [51]:
(30-mean_x2) /std_x2

-1.0975012942630598

In [60]:
sc = Binarizer(threshold=3)

In [57]:
XminMaxScal.transform(X) # scalee the values using formula

NameError: name 'XminMaxScal' is not defined

In [58]:
newX = sc.fit_transform(X)

In [59]:
newX

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [61]:
sc = Normalizer()

In [65]:
kncc

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [66]:
df.head()

diameter  weight FruitName
0       3.0      30    Banana
1       6.0     100     Apple
2       6.1      95     Apple
3       3.2      35    Banana
4       5.5      80     Apple

In [68]:
sc = StandardScaler()

In [71]:
X_train_new = sc.fit_transform(X_train)

In [72]:
X_test_new = sc.transform(X_test)

In [73]:
kncc.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [75]:
kncc.predict(X_test_new)

array(['Banana', 'Banana', 'Banana', 'Banana', 'Banana', 'Banana',
       'Banana'], dtype=object)

Scalar provies 3 methods:
------------------------
    fit()
    transform()
    fit_transform()