In [86]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [87]:
df=pd.read_csv('sample_data/mnist_train_small.csv',header=None)
X_train=df.iloc[:,1:].values
y_train=df.iloc[:,0].values

df=pd.read_csv('sample_data/mnist_test.csv',header=None)
X_test=df.iloc[:,1:].values
y_test=df.iloc[:,0].values

X_train=X_train/255.0
X_test = X_test/255.0

In [88]:
model = Sequential()
h1=Dense(400,activation='relu')
h2=Dense(160,activation='relu')
out = Dense(10,activation='softmax')

model.add(h1)
model.add(h2)
model.add(out)

model.compile(loss = "sparse_categorical_crossentropy", optimizer = 'rmsprop',metrics = ['accuracy'])
model.fit(X_train,y_train,epochs=15,batch_size=60)

Epoch 1/15
334/334 [==============================] - 2s 7ms/step - loss: 0.3297 - accuracy: 0.8997
Epoch 2/15
334/334 [==============================] - 2s 7ms/step - loss: 0.1349 - accuracy: 0.9597
Epoch 3/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0870 - accuracy: 0.9730
Epoch 4/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0559 - accuracy: 0.9819
Epoch 5/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0379 - accuracy: 0.9876
Epoch 6/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0299 - accuracy: 0.9906
Epoch 7/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0191 - accuracy: 0.9938
Epoch 8/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0168 - accuracy: 0.9944
Epoch 9/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0128 - accuracy: 0.9959
Epoch 10/15
334/334 [==============================] - 2s 7ms/step - loss: 0.0088 - accuracy: 0.9973

In [89]:
'''model = Sequential()
h1=Dense(400,activation='relu')
h2=Dense(150,activation='relu')
out = Dense(10,activation='softmax')

model.add(h1)
model.add(h2)
model.add(out)

model.compile(loss = "sparse_categorical_crossentropy", optimizer = 'adam',metrics = ['accuracy'])
model.fit(X_train,y_train,epochs=15,batch_size=60)'''

'model = Sequential()\nh1=Dense(400,activation=\'relu\')\nh2=Dense(150,activation=\'relu\')\nout = Dense(10,activation=\'softmax\')\n\nmodel.add(h1)\nmodel.add(h2)\nmodel.add(out)\n\nmodel.compile(loss = "sparse_categorical_crossentropy", optimizer = \'adam\',metrics = [\'accuracy\'])\nmodel.fit(X_train,y_train,epochs=15,batch_size=60)'

In [90]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.1886 - accuracy: 0.9764


[0.18856482207775116, 0.9764000177383423]

In [91]:
import cv2
gray=cv2.imread('2.jpeg',0)
gray=gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray), axis=-1)

array([2])

In [92]:

gray=cv2.imread('4.png',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([4])

In [93]:
gray=cv2.imread('5.jpeg',0)
gray=gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray), axis=-1)

array([6])

In [94]:
gray=cv2.imread('8.png',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([8])

In [95]:
gray=cv2.imread('0.png',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([0])

In [96]:
gray=cv2.imread('9.png',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([9])

In [97]:
gray=cv2.imread('3.png',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([3])

In [98]:
gray=cv2.imread('1.jpeg',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([1])

In [99]:
gray=cv2.imread('3.png',0)
gray =gray.reshape(1,-1)
gray=gray/255.0
np.argmax(model.predict(gray),axis=-1)

array([3])